#!/bin/sh

[ -n "$DEVICE" ] || exit 0
[ "$ACTION" = ifup ] && {
    enabled=$(uci get hfscscript.global.enabled 2>/dev/null)
    if [ "$enabled" = "1" ]; then
        /etc/init.d/SimpleHFSCgamerscript enable
        /etc/init.d/SimpleHFSCgamerscript restart
        logger -t SimpleHFSCgamerscript "Reloading SimpleHFSCgamerscript.sh due to $ACTION of $INTERFACE ($DEVICE)"
    else
        logger -t SimpleHFSCgamerscript "SimpleHFSCgamerscript is disabled in the configuration. Not executing the script."
    fi
}
